package demo.books;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.Date;

import com.jdbc.demo.ConnectionFactory;

public class GenerateAutoGeneratedKeyAndPlayWithDate {
	
	public static void main(String[] args) {
		final String ADD_BOOK_QUERY = "insert into books(isbn, title, author, pubDate, price) values (?, ?, ?, ?, ?)";
		
		
		String date = "05/09/2014";
		DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
		LocalDate dateParse = LocalDate.parse(date, fmt);
		java.sql.Date sqlDate = java.sql.Date.valueOf(dateParse);
		
		
		Connection conn;
		
		 

		try {
			conn  = ConnectionFactory.getConnection();
			PreparedStatement pstmt = conn.prepareStatement(ADD_BOOK_QUERY, Statement.RETURN_GENERATED_KEYS);
			
			pstmt.setString(1, "M132");
			pstmt.setString(2, "Glass fish");
			pstmt.setString(3, "valli");
			pstmt.setObject(4, sqlDate);
			pstmt.setInt(5, 200);
			
			int rows = pstmt.executeUpdate();
			assert(rows > 0);
			//we want to get auto gen key
			

			ResultSet rs = pstmt.getGeneratedKeys();
			if(rs.next()) {
			System.out.println(rs.getInt(1));
			}
			
			
			System.out.println("done");
		
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
