package demo.books;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.Date;

import com.jdbc.demo.ConnectionFactory;

public class GenerateAutoGeneratedKeyAndPlayWithDate {
	
	public static void main(String[] args) {
		final String ADD_BOOK_QUERY = "insert into books(isbn, title, author, pubDate, price) values (?, ?, ?, ?, ?)";
		
		
		LocalDate date = LocalDate.of(2011, Month.JUNE, 1);
		
		
		Connection conn;
		
		try {
			conn  = ConnectionFactory.getConnection();
			PreparedStatement pstmt = conn.prepareStatement(ADD_BOOK_QUERY, Statement.RETURN_GENERATED_KEYS);
			pstmt.setString(1, "YW114");
			pstmt.setString(2, "Spring");
			pstmt.setString(3, "Jagadeesh");
			pstmt.setObject(4, date);
			pstmt.setInt(5, 500);
			
			pstmt.executeUpdate();
			
			//we want to get auto gen key
			
			ResultSet rs = pstmt.getGeneratedKeys();
			if(rs.next()) {
				System.out.println(rs.getInt(1));
			}
			
			System.out.println("done");
		
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
