package demo.books;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.jdbc.demo.ConnectionFactory;

public class GenerateAutoGeneratedKeyAndPlayWithDate2Java8Date {
	
	public static void main(String[] args) {
		final String ADD_BOOK_QUERY = "insert into books(isbn, title, author, pubDate, price) values (?, ?, ?, ?, ?)";
		
		
		SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
	
			Date date = new Date("11/11/2020");
			try {
				date = format.parse("11/11/2020");
			} catch (ParseException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		
		
		Connection conn;
		
		try {
			conn  = ConnectionFactory.getConnection();
			PreparedStatement pstmt = conn.prepareStatement(ADD_BOOK_QUERY, Statement.RETURN_GENERATED_KEYS);
			pstmt.setString(1, "A1214");
			pstmt.setString(2, "AI");
			pstmt.setString(3, "Ram");
			pstmt.setDate(4, new java.sql.Date(date.getDate()));
			pstmt.setInt(5, 2000);
			
			pstmt.executeUpdate();
			
			//we want to get auto gen key
			
			ResultSet rs = pstmt.getGeneratedKeys();
			if(rs.next()) {
				System.out.println(rs.getInt(1));
			}
			
			System.out.println("done");
		
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
